import {MigrationInterface, QueryRunner} from "typeorm";

export class entidadCliente1669408280859 implements MigrationInterface {
    name = 'entidadCliente1669408280859'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId" FROM "reclamos"`);
        await queryRunner.query(`DROP TABLE "reclamos"`);
        await queryRunner.query(`ALTER TABLE "temporary_reclamos" RENAME TO "reclamos"`);
        await queryRunner.query(`CREATE TABLE "temporary_prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_prestacionServicio"("id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "temporary_prestacionServicio" RENAME TO "prestacionServicio"`);
        await queryRunner.query(`CREATE TABLE "temporary_reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId" FROM "reclamos"`);
        await queryRunner.query(`DROP TABLE "reclamos"`);
        await queryRunner.query(`ALTER TABLE "temporary_reclamos" RENAME TO "reclamos"`);
        await queryRunner.query(`CREATE TABLE "temporary_prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_prestacionServicio"("id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "temporary_prestacionServicio" RENAME TO "prestacionServicio"`);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "email" varchar NOT NULL, "phone" integer NOT NULL, "city" varchar NOT NULL, "state" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_fba0b74c9d1e77460132d34c2d0" FOREIGN KEY ("clienteId") REFERENCES "clientes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId" FROM "reclamos"`);
        await queryRunner.query(`DROP TABLE "reclamos"`);
        await queryRunner.query(`ALTER TABLE "temporary_reclamos" RENAME TO "reclamos"`);
        await queryRunner.query(`CREATE TABLE "temporary_prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_10d4c2fb4c1108c90c778eb43f7" FOREIGN KEY ("clienteId") REFERENCES "clientes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_prestacionServicio"("id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "temporary_prestacionServicio" RENAME TO "prestacionServicio"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "prestacionServicio" RENAME TO "temporary_prestacionServicio"`);
        await queryRunner.query(`CREATE TABLE "prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "prestacionServicio"("id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "temporary_prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "temporary_prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "reclamos" RENAME TO "temporary_reclamos"`);
        await queryRunner.query(`CREATE TABLE "reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "clienteId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId" FROM "temporary_reclamos"`);
        await queryRunner.query(`DROP TABLE "temporary_reclamos"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`ALTER TABLE "prestacionServicio" RENAME TO "temporary_prestacionServicio"`);
        await queryRunner.query(`CREATE TABLE "prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "prestacionServicio"("id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "clienteId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "temporary_prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "temporary_prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "reclamos" RENAME TO "temporary_reclamos"`);
        await queryRunner.query(`CREATE TABLE "reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "clienteId", "tecnicoId" FROM "temporary_reclamos"`);
        await queryRunner.query(`DROP TABLE "temporary_reclamos"`);
        await queryRunner.query(`ALTER TABLE "prestacionServicio" RENAME TO "temporary_prestacionServicio"`);
        await queryRunner.query(`CREATE TABLE "prestacionServicio" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, "servicioId" varchar NOT NULL, "insumoId" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "tipoPrestacion" varchar NOT NULL, CONSTRAINT "FK_1ee88aa5f50879cf006651011bc" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_c7685731e63b58a1aa256b89e8b" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3c5ba1eee5e8a371b2630a6738f" FOREIGN KEY ("servicioId") REFERENCES "servicios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9b3df4683625097a4dc55a32a48" FOREIGN KEY ("insumoId") REFERENCES "insumos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "prestacionServicio"("id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion") SELECT "id", "userId", "tecnicoId", "servicioId", "insumoId", "created_at", "updated_at", "tipoPrestacion" FROM "temporary_prestacionServicio"`);
        await queryRunner.query(`DROP TABLE "temporary_prestacionServicio"`);
        await queryRunner.query(`ALTER TABLE "reclamos" RENAME TO "temporary_reclamos"`);
        await queryRunner.query(`CREATE TABLE "reclamos" ("id" varchar PRIMARY KEY NOT NULL, "tipoReclamo" varchar NOT NULL, "numeroReclamo" integer NOT NULL, "fecha" datetime NOT NULL, "estado" varchar NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "userId" varchar NOT NULL, "tecnicoId" varchar NOT NULL, CONSTRAINT "FK_18fed8d155580d244083869d4d6" FOREIGN KEY ("tecnicoId") REFERENCES "tecnicos" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0826853828ae84870a05f1a801d" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reclamos"("id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId") SELECT "id", "tipoReclamo", "numeroReclamo", "fecha", "estado", "created_at", "updated_at", "userId", "tecnicoId" FROM "temporary_reclamos"`);
        await queryRunner.query(`DROP TABLE "temporary_reclamos"`);
    }

}
